=== 15736889361/stendhal/data/conf/creatures.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>


<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                   elementFormDefault="qualified">

	<xsd:element name="creatures" type="Creatures"/>

	<xsd:element name="creature" type="Creature"/>


	<xsd:complexType name="Creatures">
		<xsd:sequence>
			<xsd:element name="creature" type="Creature" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="Creature">
		<xsd:sequence>
			<xsd:element name="type" type="Type" minOccurs="1"/>
			<xsd:element name="attributes" type="Attributes" minOccurs="1"/>
			<xsd:element name="level" type="Level" minOccurs="1"/>
			<xsd:element name="experience" type="Experience" minOccurs="1"/>
			<xsd:element name="drops" type="Drops" minOccurs="0"/>
			<xsd:element name="slots" type="Slots" minOccurs="0"/>
			<xsd:element name="equips" type="Equips" minOccurs="0"/>
			<xsd:element name="ai" type="Ai" minOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string"/>
		<xsd:attribute name="quantity" type="xsd:string"/>
		<xsd:attribute name="probability" type="xsd:nonNegativeInteger"/>
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Item" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Says" minOccurs="0"/>
			<xsd:element name="profile" type="Profile" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Noise" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Noise">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="params" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string"/>
		<xsd:attribute name="subclass" type="xsd:string"/>
		<xsd:attribute name="tileid" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="head" type="xsd:string" minOccurs="0"/>
			<xsd:element name="lhand" type="xsd:string" minOccurs="0"/>
			<xsd:element name="rhand" type="xsd:string" minOccurs="0"/>
			<xsd:element name="body" type="xsd:string" minOccurs="0"/>
			<xsd:element name="legs" type="xsd:string" minOccurs="0"/>
			<xsd:element name="feet" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== 15736889361/stendhal/data/conf/creatures/troll.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd ">
    
  <creature name="troll">
    <type class="troll" subclass="troll" tileid="troll.png:0"/>
    <description>You see a troll, be careful in his terrain.</description>
    <attributes>
      <atk value="135"/>
      <def value="34"/>
      <hp value="60"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="10"/>
    <experience value="110"/>
    <respawn value="1210"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[3,7]" probability="90.0"/>
      <item value="chain armor" quantity="[1,1]" probability="3.0"/>
      <item value="chain legs" quantity="[1,1]" probability="2.0"/>
      <item value="enhanced chainmail" quantity="[1,1]" probability="0.05"/>
      <item value="flail" quantity="[1,1]" probability="30.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  <creature name="red troll">
    <type class="troll" subclass="red_troll" tileid="troll.png:2"/>
    <description>You see a red troll, he's burning with anger.</description>
    <attributes>
      <atk value="190"/>
      <def value="34"/>
      <hp value="110"/>
      <speed value="0.7"/>
      <size value="1,1"/>
    </attributes>
    <level value="16"/>
    <experience value="200"/>
    <respawn value="1230"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[3,17]" probability="90.0"/>
      <item value="scale armor" quantity="[1,1]" probability="3.0"/>
      <item value="chain legs" quantity="[1,1]" probability="4.0"/>
      <item value="flail" quantity="[1,1]" probability="30.0"/>
      <item value="ugmash" quantity="[1,1]" probability="0.0001"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
   
</creatures>
