=== 15736889361/stendhal/data/conf/items.xsd
<?xml version="1.0" encoding="ISO-8859-1"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"                   elementFormDefault="qualified">	<xsd:element name="items" type="Items"/>	<xsd:element name="item" type="Item"/>	<xsd:complexType name="Items">		<xsd:sequence>			<xsd:element name="item" type="Item" maxOccurs="unbounded"/>		</xsd:sequence>	</xsd:complexType>		<xsd:complexType name="Item">		<xsd:sequence>			<xsd:element name="type" type="Type" minOccurs="1"/>			<xsd:element name="description" type="xsd:string" minOccurs="0"/>			<xsd:element name="stackable" type="xsd:string" minOccurs="0"/>			<xsd:element name="attributes" type="Attributes" minOccurs="0"/>			<xsd:element name="weight" type="Weight" minOccurs="1"/>			<xsd:element name="equipable" type="Equipable" minOccurs="1"/>		</xsd:sequence>		<xsd:attribute name="name" type="xsd:string"/>	</xsd:complexType>	<xsd:complexType name="Type">		<xsd:attribute name="class" type="xsd:string"/>		<xsd:attribute name="subclass" type="xsd:string"/>	</xsd:complexType>	<xsd:complexType name="Attributes">		<xsd:sequence>			<xsd:element name="atk" minOccurs="0">				<xsd:complexType>					<xsd:attribute name="value" type="xsd:positiveInteger"/>				</xsd:complexType>			</xsd:element>			<xsd:element name="def" minOccurs="0">				<xsd:complexType>					<xsd:attribute name="value" type="xsd:positiveInteger"/>				</xsd:complexType>			</xsd:element>			<xsd:element name="hp" minOccurs="0">				<xsd:complexType>					<xsd:attribute name="value" type="xsd:positiveInteger"/>				</xsd:complexType>			</xsd:element>			<xsd:element name="speed" minOccurs="0">				<xsd:complexType>					<xsd:attribute name="value" type="xsd:decimal"/>				</xsd:complexType>			</xsd:element>			<xsd:element name="size" minOccurs="0">				<xsd:complexType>					<xsd:attribute name="value" type="xsd:string"/>				</xsd:complexType>			</xsd:element>			<xsd:element name="quantity" minOccurs="0">				<xsd:complexType>					<xsd:attribute name="value" type="xsd:positiveInteger"/>				</xsd:complexType>			</xsd:element>			<xsd:element name="amount" minOccurs="0">				<xsd:complexType>					<xsd:attribute name="value" type="xsd:integer"/>				</xsd:complexType>			</xsd:element>			<xsd:element name="regen" minOccurs="0">				<xsd:complexType>					<xsd:attribute name="value" type="xsd:integer"/>				</xsd:complexType>			</xsd:element>			<xsd:element name="frequency" minOccurs="0">				<xsd:complexType>					<xsd:attribute name="value" type="xsd:positiveInteger"/>				</xsd:complexType>			</xsd:element>			<xsd:element name="infostring" minOccurs="0">				<xsd:complexType>					<xsd:attribute name="value" type="xsd:string"/>				</xsd:complexType>			</xsd:element>		</xsd:sequence>	</xsd:complexType>	<xsd:complexType name="Weight">		<xsd:attribute name="value" type="xsd:decimal"/>	</xsd:complexType>	<xsd:complexType name="Equipable">		<xsd:sequence>			<xsd:element name="slot" type="Slot" maxOccurs="7"/>		</xsd:sequence>	</xsd:complexType>	<xsd:complexType name="Slot">		<xsd:attribute name="name" type="xsd:string"/>	</xsd:complexType></xsd:schema>

=== 15736889361/stendhal/data/conf/items/documents.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">

  <item name="note">
    <type class="documents" subclass="paper" tileid="-1"/>
    <description>You see a note.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="coupon">
    <type class="documents" subclass="coupon" tileid="-1"/>
    <description>You see a coupon.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="closed envelope">
    <type class="documents" subclass="closed_envelope" tileid="-1"/>
    <description/>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="opened envelope">
    <type class="documents" subclass="opened_envelope" tileid="-1"/>
    <description/>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="sealed envelope">
    <type class="documents" subclass="sealed_envelope" tileid="-1"/>
    <description/>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="unsealed envelope">
    <type class="documents" subclass="unsealed_envelope" tileid="-1"/>
    <description/>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
    </equipable>
  </item>
  
    <item name="assassins id">
    <type class="documents" subclass="license" tileid="-1"/>
    <description>You see an assassin's ID. Perhaps this can be put to good use.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
       <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
      <slot name="keyring"/>
    </equipable>
  </item>

  <item name="map">
    <type class="documents" subclass="mapwithgrid" tileid="-1"/>
    <description/>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="scroll">
    <type class="documents" subclass="scroll" tileid="-1"/>
    <description>You see a rolled up scroll.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
       <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="ice scroll">
    <type class="documents" subclass="ice_scroll" tileid="-1"/>
    <description>You see a scroll, circled by ice crystals. You can feel its cold aura.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
       <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>
</items>

=== 15736889361/stendhal/data/conf/items/capturetheflag.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">

  <!-- capture-the-flag stuff -->

  <item name="flag">
    <type class="misc" subclass="teddy" tileid="-1"/>
    <description>You see a flag. Its soft and cuddly, and children love them.</description>

    <implementation class-name="games.stendhal.server.entity.item.CaptureTheFlagFlag"/>
    
    <attributes>
    </attributes>

    <weight value="1.0"/>
    <value  value="1"/>
    
    <equipable>
      <slot name="rhand"/>
      <slot name="lhand"/>
      <slot name="ground"/>
            
      <!-- i think that hand-only is a good policy -->
      <!-- <slot name="content"/> -->
      <!-- <slot name="bag"/>     -->
    </equipable>
  </item>


</items>

=== 15736889361/stendhal/data/conf/items/tokens.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">

  <item name="arrow_game_token">
    <type class="token" subclass="darkyellow_round_token" tileid="-1"/>
    <description>You see a token, that when placed in the right spot could point you in the right direction.</description>
    <implementation class-name="games.stendhal.server.entity.item.token.Token"/>
    <attributes>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
    </equipable>
  </item>

  <item name="x_board_token">
    <type class="token" subclass="red_x_token" tileid="-1"/>
    <description>You see an X token.</description>
    <implementation class-name="games.stendhal.server.entity.item.token.BoardToken"/>
    <attributes>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
    </equipable>
  </item>

  <item name="o_board_token">
    <type class="token" subclass="blue_o_token" tileid="-1"/>
    <description>You see an O token.</description>
    <implementation class-name="games.stendhal.server.entity.item.token.BoardToken"/>
    <attributes>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
    </equipable>
  </item>
</items>

=== 15736889361/stendhal/data/conf/items/flowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">

  <item name="rhosyd">
    <type class="flower" subclass="exotic_flower" tileid="-1"/>
    <description>You see a beautiful and rare rhosyd flower.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="rose">
    <type class="flower" subclass="rose" tileid="-1"/>
    <description>You see a single red rose. It smells heavenly.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
     <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item> 

  <item name="lilia">
    <type class="flower" subclass="lilia" tileid="-1"/>
    <description>You see a lilia, a single precious bloom.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
     <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="daisies">
    <type class="flower" subclass="daisies" tileid="-1"/>
    <description>You see a bunch of daisies. They are cheap and cheerful!</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
     <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

</items>

=== 15736889361/stendhal/data/conf/items/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">
  
  <item name="crystal of anger">
    <type class="gem" subclass="crystal_red" tileid="-1" />
    <description>You see a #crystal #of #anger.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item" />
    <attributes>
      <quantity value="1" />
      <max_quantity value="2147483647" />
    </attributes>
    <weight value="0.1" />
    <value value="100" />
    <equipable>
      <slot name="ground" />
      <slot name="content" />
      <slot name="lhand" />
      <slot name="rhand" />
      <slot name="head" />
      <slot name="bag" />
    </equipable>
  </item>
  
  <item name="crystal of fear">
    <type class="gem" subclass="crystal_purple" tileid="-1" />
    <description>You see a #crystal #of #fear.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item" />
    <attributes>
      <quantity value="1" />
      <max_quantity value="2147483647" />
    </attributes>
    <weight value="0.1" />
    <value value="100" />
    <equipable>
      <slot name="ground" />
      <slot name="content" />
      <slot name="lhand" />
      <slot name="rhand" />
      <slot name="head" />
      <slot name="bag" />
    </equipable>
  </item>
  
  <item name="crystal of joy">
    <type class="gem" subclass="crystal_yellow" tileid="-1" />
    <description>You see a #crystal #of #joy.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item" />
    <attributes>
      <quantity value="1" />
      <max_quantity value="2147483647" />
    </attributes>
    <weight value="0.1" />
    <value value="100" />
    <equipable>
      <slot name="ground" />
      <slot name="content" />
      <slot name="lhand" />
      <slot name="rhand" />
      <slot name="head" />
      <slot name="bag" />
    </equipable>
  </item>
  
  <item name="crystal of love">
    <type class="gem" subclass="crystal_pink" tileid="-1" />
    <description>You see a #crystal #of #love.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item" />
    <attributes>
      <quantity value="1" />
      <max_quantity value="2147483647" />
    </attributes>
    <weight value="0.1" />
    <value value="100" />
    <equipable>
      <slot name="ground" />
      <slot name="content" />
      <slot name="lhand" />
      <slot name="rhand" />
      <slot name="head" />
      <slot name="bag" />
    </equipable>
  </item>
  
  <item name="crystal of peace">
    <type class="gem" subclass="crystal_blue" tileid="-1" />
    <description>You see a #crystal #of #peace.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item" />
    <attributes>
      <quantity value="1" />
      <max_quantity value="2147483647" />
    </attributes>
    <weight value="0.1" />
    <value value="100" />
    <equipable>
      <slot name="ground" />
      <slot name="content" />
      <slot name="lhand" />
      <slot name="rhand" />
      <slot name="head" />
      <slot name="bag" />
    </equipable>
  </item>
  
</items>

=== 15736889361/stendhal/data/conf/items/missiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">
    <item name="snowball">
    <type class="missile" subclass="snowballs" tileid="-1"/>
    <description>You see snowballs. You can throw them on your friends or put it in your bag to keep your fish fresh. But be carfully, there could be little stones in it.</description>
    <implementation class-name="games.stendhal.server.entity.item.NoStatsStackableItem"/>    <attributes>
      <atk value="-1"/>
      <range value="8"/>
      <quantity value="1"/>
    </attributes>
    <weight value="0.1"/>
    <value value="80"/>
    <damage type="ice"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
    </equipable>
  </item>
  
   <item name="vomit">
    <type class="missile" subclass="vomit" tileid="-1"/>
    <description>You see a pile of vomit. Gross!</description>
    <implementation class-name="games.stendhal.server.entity.item.NoStatsStackableItem"/>    <attributes>
      <atk value="-1"/>
      <range value="5"/>
      <quantity value="1"/>
    </attributes>
    <weight value="0.1"/>
    <value value="2"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
    </equipable>
  </item>
  
  <item name="dart">
    <type class="missile" subclass="dart" tileid="-1"/>
    <description>You see a dart. You'll need to be close before you can use it as a missile. Stand square on, not diagonally, for the best results.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <atk value="2"/>
      <range value="2"/>
      <quantity value="1"/>
    </attributes>
    <weight value="0.1"/>
    <value value="80"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="power dart">
    <type class="missile" subclass="dart" tileid="-1"/>
    <description>You see a power dart. You'll need to be close before you can use it as a missile. Stand square on, not diagonally, for the best results. </description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <atk value="4"/>
      <range value="2"/>
      <quantity value="1"/>
    </attributes>
    <weight value="0.1"/>
    <value value="640"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="shuriken">
    <type class="missile" subclass="shuriken" tileid="-1"/>
    <description>You see a shuriken. You'll need to be close before you can use it as a missile. Stand square on, not diagonally, for the best results.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <atk value="6"/>
      <range value="2"/>
      <quantity value="1"/>
    </attributes>
    <weight value="0.1"/>
    <value value="2160"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="wooden spear">
    <type class="missile" subclass="wooden_spear" tileid="-1"/>
    <description>You see a wooden spear. You can attack at a distance with this primitive weapon. Stand square on, not diagonally, for the best results.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <atk value="10"/>
      <range value="4"/>
      <quantity value="1"/>
    </attributes>
    <weight value="0.1"/>
    <value value="10000"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
    </equipable>
  </item>
</items>

=== 15736889361/stendhal/data/conf/items/relics.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">

  <item name="angel figurine">
    <type class="relic" subclass="angel_figurine" tileid="-1"/>
    <description>You see a sparkling angel figurine.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
       <quantity value="1"/>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

</items>
