=== 15736889361/stendhal/data/conf/quests.xsd
<?xml version="1.0" encoding="ISO-8859-1"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"                   elementFormDefault="qualified"
                   xmlns="http://arianne.sf.net/stendhal/schema/quests"
                   targetNamespace="http://arianne.sf.net/stendhal/schema/quests">	<xsd:element name="quests" type="Quests"/>	<xsd:element name="quest" type="Quest"/>	<xsd:complexType name="Quests">		<xsd:sequence>			<xsd:element name="quest" type="Quest" maxOccurs="unbounded"/>		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Quest">		<xsd:sequence>			<xsd:element name="title" type="xsd:string" minOccurs="1"/>
			<xsd:element name="repeatable" type="Repeatable" minOccurs="1"/>
			<xsd:element name="description" type="xsd:string" minOccurs="1"/>
			<xsd:element name="gm-description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="history" type="History" minOccurs="0"/>			<xsd:element name="hints" type="Hints" minOccurs="0"/>		</xsd:sequence>		<xsd:attribute name="name" type="xsd:string" use="required"/>	</xsd:complexType>	<xsd:complexType name="Repeatable">
		<xsd:attribute name="done"     type="xsd:boolean" use="required"/>
		<xsd:attribute name="failed"   type="xsd:boolean" use="optional"/>
		<xsd:attribute name="rejected" type="xsd:boolean" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="History">		<xsd:sequence>			<xsd:element name="entry" type="Entry" minOccurs="0" maxOccurs="unbounded" />		</xsd:sequence>	</xsd:complexType>	<xsd:complexType name="Hints">
		<xsd:sequence>
			<xsd:element name="entry" type="Entry" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Entry">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="name" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>	</xsd:complexType></xsd:schema>

=== 15736889361/stendhal/data/conf/quests.xml
<?xml version="1.0" encoding="ISO-8859-1"?>



<!--
quests.xml
This file contains all the descriptive data about quests.

State: EXPERIMENTAL to help me think about a quest system

-->

<quests xmlns="http://arianne.sf.net/stendhal/schema/quests"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://arianne.sf.net/stendhal/schema/quests quests.xsd">


	<quest name="ArmorForDagobert">
		<title>Armor For Dagobert</title>
		<repeatable done="false" rejected="true" />
		<description>
			Dagobert, the consultant at the bank of Semos, asked me to 
			find a leather_cuirass for him.
		</description>
		<history>
			<entry name="FIRST_CHAT">I have met Dagobert. He is the consultant at the bank in Semos.</entry>
			<entry name="QUEST_ACCEPTED">I promissed to find a leather_cuirass for him because he has been robbed.</entry>
			<entry name="QUEST_REJECTED">He asked me to find a leather_cuirass but I rejected his request.</entry>
			<entry name="FOUND_ITEM">I found a leather_cuirass and will take it to Dagobert.</entry>
			<entry name="DONE">I took the leather_cuirass to Dagobert. He thanked me and gave a small reward.</entry>
		</history>
		<hints>
			<entry name="DROP_ITEM">I see that you will take a leather_cuirass from a dead cyclops.</entry>
			<entry name="FIND_CREATURE">I see that you will fight some cyclopes living in the dungeon deep under Semos.</entry>
		</hints>
	</quest>

	<quest name="IntroducePlayers">
		<title>Helping Tad</title>
		<repeatable done="false" />
		<description>
			First quest: Tad, a boy in Semos Townhall, needs help.
		</description>
		<history>
			<entry name="FIRST_CHAT">I have met Tad in Semos Townhall</entry>
			<entry name="GET_FLASK">He asked me to buy a flask from Margaret in Semos Tavern.</entry>
			<entry name="GOT_FLASK">I got a flask an will bring it to Tad soon.</entry>
			<entry name="FLASK_TO_ILISA">Tad asked me to take the flask to ilisa at Semos Temple.</entry>
			<entry name="GET_HERB">Ilisa asked me to get a herb called Arandula which I can find north of Semos, near the tree grove.</entry>
			<entry name="GOT_HERB">I found some Arandula herbs and will bring them to ilisa.</entry>
			<entry name="TALK_TO_TAD">Ilisa created a powerful potion to help Tad. She asked me to tell him that it is ready.</entry>
			<entry name="DONE">Tad thanked me.</entry>
		</history>
	</quest>
</quests>
