=== 15736889361/stendhal/data/conf/zones/zones.dtd
<!ELEMENT zones (zone*)>
<!ELEMENT zone (title?, (configurator | portal | entity)*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT configurator (attribute*)>
<!ELEMENT attribute (#PCDATA)>
<!ELEMENT portal (destination?, implementation?)>
<!ELEMENT destination EMPTY>
<!ELEMENT implementation (attribute*)>
<!ELEMENT entity (implementation)>

<!ATTLIST zone name CDATA #REQUIRED>
<!ATTLIST zone file CDATA #REQUIRED>
<!ATTLIST configurator class-name CDATA #REQUIRED>
<!ATTLIST attribute name CDATA #REQUIRED>
<!ATTLIST portal x CDATA #REQUIRED>
<!ATTLIST portal y CDATA #REQUIRED>
<!ATTLIST portal ref CDATA #REQUIRED>
<!ATTLIST portal replacing CDATA #IMPLIED>
<!ATTLIST destination zone CDATA #REQUIRED>
<!ATTLIST destination ref CDATA #REQUIRED>
<!ATTLIST implementation class-name CDATA #REQUIRED>
<!ATTLIST entity x CDATA #REQUIRED>
<!ATTLIST entity y CDATA #REQUIRED>

=== 15736889361/stendhal/data/conf/zones/misc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE zones SYSTEM "zones.dtd"> -->
<zones>

 <!-- XXX - Does this belong with a major area??? -->
 <zone name="-2_kotoch_entrance" level="-2" x="500160" y="500032" file="sub_2_kotoch_entrance.xstend">
 </zone>


 <zone name="int_afterlife" file="int_afterlife.xstend">
  <portal x="30" y="6" ref="exit_left">
   <destination zone="int_semos_temple" ref="restart_life"/>
  </portal>

  <portal x="31" y="6" ref="exit_center">
   <destination zone="int_semos_temple" ref="restart_life"/>
  </portal>

  <portal x="32" y="6" ref="exit_right">
   <destination zone="int_semos_temple" ref="restart_life"/>
  </portal>
            
  <entity x="29" y="22">
   <implementation class-name="games.stendhal.server.entity.Sign">
    <parameter name="text">
Sorry, you have died.
You lost some of your items and 10% of your experience points.
Be more careful in the future!

Walk on, and you will be returned to the land of the living...
    </parameter>
   </implementation>
  </entity>

  <entity x="33" y="22">
   <implementation class-name="games.stendhal.server.entity.Sign">
    <parameter name="text">
Sorry, you have died.
You lost some of your items and 10% of your experience points.
Be more careful in the future!

Walk on, and you will be returned to the land of the living...
    </parameter>
   </implementation>
  </entity>
 </zone>

 <zone name="int_admin_playground" file="int_admin_playground.xstend">
 </zone>

 <zone name="int_pathfinding" file="int_pathfinding.xstend">
  <configurator class-name="games.stendhal.server.maps.FeaturesTestArea" />

  <portal x="50" y="10" ref="locked_outside">
   <destination zone="int_pathfinding" ref="locked_inside"/>
   <implementation class-name="games.stendhal.server.entity.portal.LockedDoor">
    <parameter name="class">skulldoor</parameter>
    <parameter name="direction">down</parameter>
    <parameter name="key">key_golden</parameter>
   </implementation>
  </portal>

  <portal x="50" y="12" ref="locked_inside">
   <destination zone="int_pathfinding" ref="locked_outside"/>
  </portal>
 </zone>

</zones>

=== 15736889361/stendhal/data/conf/zones/kirdneh.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE zones SYSTEM "zones.dtd"> -->
<zones>
 <!--
   ** Load zones. Written from left to right and from top to bottom.
   ** Please respect it!
   -->

 <!-- Level 6 -->

 <!-- Level 5 -->

 <!-- Level 4 -->

 <!-- Level 3 -->

 <!-- Level 2 -->

 <!-- Level 1 -->

 <!-- Level 0 (Ground) -->

 <zone name="0_kirdneh_city" level="0" x="500000" y="500512" file="Level 0/kirdneh/city.tmx">
  <portal x="50" y="7" ref="diving_board">
   <destination zone="0_kirdneh_city" ref="pool"/>
   <attribute name="hidden"/>
  </portal>
  <portal x="32" y="89" ref="tavern">
   <destination zone="int_kirdneh_inn" ref="entrance"/>
  </portal>
  <portal x="48" y="7" ref="pool">
   <implementation class-name="games.stendhal.server.entity.portal.OneWayPortalDestination"/>
  </portal>
  <portal x="77" y="58" ref="townhall">
   <destination zone="int_kirdneh_townhall" ref="entrance"/>
  </portal>
  <entity x="20" y="57">
    <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
    <attribute name="description">You see a hot hot barbecue.</attribute>
  </entity>
  <entity x="102" y="72">
    <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
    <attribute name="description">You see a sizzling hot barbecue.</attribute>
  </entity>
  <entity x="23" y="101">
    <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
    <attribute name="description">You see a sizzling barbecue.</attribute>
  </entity>
  <entity x="24" y="101">
    <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
    <attribute name="description">You see a burning hot grill.</attribute>
  </entity>
  <entity x="58" y="100">
    <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
    <attribute name="description">You see a very hot grill.</attribute>
  </entity>
  <entity x="59" y="100">
    <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
    <attribute name="description">You see a sizzling barbecue.</attribute>
  </entity>
 </zone>

<zone name="int_kirdneh_inn" file="interiors/kirdneh/inn.tmx">
  <portal x="18" y="23" ref="entrance">
   <destination zone="0_kirdneh_city" ref="tavern"/>
  </portal>
 </zone>

<zone name="int_kirdneh_townhall" file="interiors/kirdneh/townhall.tmx">
 <portal x="19" y="23" ref="entrance">
   <destination zone="0_kirdneh_city" ref="townhall"/>
 </portal>
 <portal x="18" y="3" ref="upstair_left">
   <destination zone="int_kirdneh_townhall1" ref="downstair_left"/>
 </portal>
 <portal x="19" y="3" ref="upstair_right">
   <destination zone="int_kirdneh_townhall1" ref="downstair_right"/>
 </portal>
</zone>

<zone name="int_kirdneh_townhall1" file="interiors/kirdneh/townhall1.tmx">
 <portal x="18" y="4" ref="downstair_left">
   <destination zone="int_kirdneh_townhall" ref="upstair_left"/>
 </portal>
 <portal x="19" y="4" ref="downstair_right">
   <destination zone="int_kirdneh_townhall" ref="upstair_right"/>
 </portal>
</zone>
 <!-- Level -1 -->

 <!-- Level -2 -->

 <!-- Level -3 -->

 <!-- Level -4 -->

 <!-- Level -5 -->

 <!-- Level -6 -->

 <!-- Level -7 -->

</zones>

=== 15736889361/stendhal/data/conf/zones/kalavan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE zones SYSTEM "zones.dtd"> -->
<zones>
 <!--
   ** Load zones. Written from left to right and from top to bottom.
   ** Please respect it!
   -->


 <!--  Level 6 -->


 <!--  Level 5 -->


 <!--  Level 4 -->


 <!--  Level 3 -->


 <!--  Level 2 -->


 <!--  Level 1 -->


 <!--  Ground level -->

 <zone name="0_kalavan_castle" level="0" x="499616" y="500640" file="Level 0/kalavan/castle.tmx">
  <portal x="63" y="72" ref="castle_entrance_left">
   <destination zone="int_kalavan_castle" ref="entrance_left"/>
  </portal>
  <portal x="64" y="72" ref="castle_entrance_right">
   <destination zone="int_kalavan_castle" ref="entrance_right"/>
  </portal>
  <portal x="63" y="48" ref="castle_2_entrance_left">
   <destination zone="int_kalavan_castle_2" ref="entrance_left"/>
  </portal>
  <portal x="64" y="48" ref="castle_2_entrance_right">
   <destination zone="int_kalavan_castle_2" ref="entrance_right"/>
  </portal>
 </zone>

 <zone name="int_kalavan_castle_basement" file="interiors/kalavan/castle_basement.tmx">
  <portal x="31" y="39" ref="upstairs">
   <destination zone="int_kalavan_castle" ref="downstairs"/>
  </portal>
 </zone>

 <zone name="int_kalavan_castle" file="interiors/kalavan/castle.tmx">
  <portal x="31" y="63" ref="entrance_left">
   <destination zone="0_kalavan_castle" ref="castle_entrance_left"/>
  </portal>
  <portal x="32" y="63" ref="entrance_right">
   <destination zone="0_kalavan_castle" ref="castle_entrance_right"/>
  </portal>
  <portal x="31" y="39" ref="upstairs">
   <destination zone="int_kalavan_castle_1" ref="downstairs"/>
  </portal>
  <portal x="32" y="39" ref="downstairs">
   <destination zone="int_kalavan_castle_basement" ref="upstairs"/>
  </portal>
 </zone>

 <zone name="int_kalavan_castle_1" file="interiors/kalavan/castle_1.tmx">
  <portal x="31" y="36" ref="downstairs">
   <destination zone="int_kalavan_castle_0" ref="upstairs"/>
  </portal>
  <portal x="32" y="36" ref="upstairs">
   <destination zone="int_kalavan_castle_2" ref="downstairs"/>
  </portal>
 </zone>

 <zone name="int_kalavan_castle_2" file="interiors/kalavan/castle_2.tmx">
  <portal x="15" y="15" ref="entrance_left">
   <destination zone="0_kalavan_castle" ref="castle_2_entrance_left"/>
  </portal>
  <portal x="16" y="15" ref="entrance_right">
   <destination zone="0_kalavan_castle" ref="castle_2_entrance_right"/>
  </portal>
  <portal x="16" y="10" ref="downstairs">
   <destination zone="int_kalavan_castle_1" ref="upstairs"/>
  </portal>
 </zone>

 <zone name="0_kalavan_city" level="0" x="499616" y="500768" file="Level 0/kalavan/city.tmx">
  <entity x="63" y="10">
   <implementation class-name="games.stendhal.server.entity.Sign"/>
   <attribute name="text">Friends, welcome to Kalavan City.</attribute>
   <attribute name="class">transparent</attribute>
  </entity>
  <entity x="64" y="10">
   <implementation class-name="games.stendhal.server.entity.Sign"/>
   <attribute name="text">Enemies, beware!</attribute>
   <attribute name="class">transparent</attribute>
  </entity>
  <entity x="65" y="10">
   <implementation class-name="games.stendhal.server.entity.Sign"/>
   <attribute name="text">Kalavan City, twinned with Deniran.</attribute>
   <attribute name="class">transparent</attribute>
  </entity>
  <entity x="3" y="29">
   <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
   <attribute name="description">You see a hot grill, for fish, meat or ham.</attribute>
  </entity>
  <entity x="3" y="30">
   <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
   <attribute name="description">You see a barbecue, and wonder where the cook is.</attribute>
  </entity>
  <entity x="123" y="13">
   <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
   <attribute name="description">You see a barbecue, ready to grill some fish. Careful, it will be hot!</attribute>
  </entity>
  <entity x="123" y="14">
   <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
   <attribute name="description">You see a barbecue for grilling meat. Just try not to burn it.</attribute>
  </entity>
  <entity x="114" y="44">
   <implementation class-name="games.stendhal.server.entity.Sign"/>
   <attribute name="text">Dear Mr Postman, please leave my mail under the mat, as birds are nesting in this mailbox.</attribute>
   <attribute name="class">transparent</attribute>
  </entity>
  <entity x="57" y="125">
   <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
   <attribute name="description">You see a grill, looks like someone is going to barbecue soon.</attribute>
  </entity>
  <entity x="58" y="125">
   <implementation class-name="games.stendhal.server.entity.WalkBlocker"/>
   <attribute name="description">You see a barbecue, ready to grill some ham. Careful, it's very hot!</attribute>
  </entity>
 </zone>


 <!--  Level -1 -->


 <!--  Level -2 -->


 <!--  Level -3 -->


 <!--  Level -4 -->


 <!--  Level -5 -->


 <!--  Level -6 -->


 <!--  Level -7 -->

</zones>

=== 15736889361/stendhal/data/conf/zones/kikareukin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE zones SYSTEM "zones.dtd"> -->
<zones>
 <!--
   ** Load zones. Written from left to right and from top to bottom.
   ** Please respect it!
   -->

 <!-- Level 6 -->

 <zone name="6_kikareukin_islands" level="6" x="499616" y="499744" file="Level 6/kikareukin/islands.tmx">
  <portal x="66" y="63" ref="exit">
   <destination zone="0_semos_mountain_n_w4" ref="kikareukin_exit"/>
  </portal>
 </zone>


 <!-- Level 5 -->

 <zone name="5_kikareukin_cave" level="5" x="499616" y="499744" file="Level 5/kikareukin/cave.tmx">
 </zone>


 <!-- Level 4 -->

 <zone name="4_kikareukin_cave" level="4" x="499616" y="499744" file="Level 4/kikareukin/cave.tmx">
 </zone>


 <!-- Level 3 -->

 <zone name="3_kikareukin_cave" level="3" x="499616" y="499744" file="Level 3/kikareukin/cave.tmx">
 </zone>


 <!-- Level 2 -->

 <zone name="2_kikareukin_cave" level="2" x="499616" y="499744" file="Level 2/kikareukin/cave.tmx">
 </zone>


 <!-- Level 1 -->

 <zone name="1_kikareukin_cave" level="1" x="499616" y="499744" file="Level 1/kikareukin/cave.tmx">
  <portal x="16" y="96" ref="entrance">
   <destination zone="0_semos_mountain_n_w4" ref="kikareukin_entrance"/>
  </portal>
 </zone>


 <!-- Level 0 (Ground) -->


 <!-- Level -1 -->


 <!-- Level -2 -->


 <!-- Level -3 -->


 <!-- Level -4 -->


 <!-- Level -5 -->


 <!-- Level -6 -->


 <!-- Level -7 -->

</zones>
